/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myjni_HelloWorld */

#ifndef _Included_myjni_HelloWorld
#define _Included_myjni_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myjni_HelloWorld
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloWorld_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloWorld
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_myjni_HelloWorld_average
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     myjni_HelloWorld
 * Method:    others
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloWorld_others
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloWorld
 * Method:    passStrfromJava
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_myjni_HelloWorld_passStrfromJava
  (JNIEnv *, jobject, jstring);

/*
 * Class:     myjni_HelloWorld
 * Method:    sumAndAverage
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_myjni_HelloWorld_sumAndAverage
  (JNIEnv *, jobject, jdoubleArray);

/*
 * Class:     myjni_HelloWorld
 * Method:    modifyInstanceMember
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloWorld_modifyInstanceMember
  (JNIEnv *, jobject);

/*
 * Class:     myjni_HelloWorld
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myjni_HelloWorld_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
